apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: april-15
  janus-idp.io/tekton: april-15
  backstage.io/kubernetes-id: april-15
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: april-15
resources: 
- deployment.yaml
- route.yaml
- service.yaml
